SDT deployment role
dell/ansible-powerflex pull request #64
Opened 2024-10-10 07:48 UTC by RayLiu7

# Description
SDT deployment role

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, pep8, linting, or security issues
- [ ] I have performed Ansible Sanity test using --docker default
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-10-10 07:49 UTC, ansible-collections-svc commented
Can one of the admins verify this patch?

2024-10-14 06:26 UTC, sachin-apa commented
run e2e

2024-10-22 05:39 UTC, sachin-apa requested changes
I See lot of common tasks in install and uninstall, Can we move them to common yml and use them accordingly in install and uninstall yml's.

2024-10-22 05:39 UTC, sachin-apa commented on playbooks/roles/host_vars/sdt1
> +powerflex_sdt_role_list: storage_and_host,storage_and_host
new line missing,

2024-10-22 05:39 UTC, sachin-apa commented on playbooks/roles/host_vars/sdt2
> +powerflex_sdt_role_list: storage_and_host,storage_and_host
new line missing,

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/defaults/main.yml
> +i_am_sure: 1
_file_glob_name_, _i_am_sure_ if these vars are not user inputs, move this to vars/main.yml
 lets follow role_name_ convention, if these are role inputs, and update the doc and arg spec accordingly.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/vars/main.yml
> +powerflex_role_environment:
I don't see a usage of this var anywhere in the task. Can you please check if this is required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +  ansible.builtin.command: scli --add_certificate --certificate_file /opt/emc/scaleio/mdm/cfg/mgmt_ca.pem
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +      ansible.builtin.command: >
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +      ansible.builtin.command: >
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +  ansible.builtin.command: scli --add_sdt --management_system_ip {{ hostname }}
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +  ansible.builtin.command: scli --login --p12_path /opt/emc/scaleio/mdm/cfg/cli_certificate.p12 --p12_password {{ password }}
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +  ignore_errors: true
Why are we ignoring error here ?

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +      ansible.builtin.command: >
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +      ansible.builtin.command: >
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +  ansible.builtin.command: scli --login --p12_path /opt/emc/scaleio/mdm/cfg/cli_certificate.p12 --p12_password {{ password }}
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +  ansible.builtin.command:
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +  ansible.builtin.command: scli --add_certificate --certificate_file /opt/emc/scaleio/mdm/cfg/mgmt_ca.pem
Its good to move the commands to vars/main.yml and duynamically replace the values as required.

2024-10-22 05:39 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +  when: ansible_distribution in ("RedHat", "CentOS", "SLES")
How are we ensuring _ansible_distribution_ value is populated ?

2024-10-24 05:47 UTC, Bhavneet-Sharma requested changes

2024-10-24 05:47 UTC, Bhavneet-Sharma commented on playbooks/roles/inventory
> +sdt2
New line is missing.

2024-10-24 05:47 UTC, Bhavneet-Sharma commented on roles/powerflex_sdt/meta/argument_spec.yml
> +          - Port used by the NVMe hosts
```suggestion
          - Port used by the NVMe hosts.
```

2024-10-24 05:47 UTC, Bhavneet-Sharma commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +- name: Add certificate file for PowerFlex version 4.x
If we are going to develop the SDT module then I would suggest that try to use the tasks of module for better reusability of code instead of directly calling the CLI commands, that will be easy to maintain and debug.

2024-10-24 05:47 UTC, Bhavneet-Sharma commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +- name: Add certificate file for PowerFlex version 4.x
That will save the login and cert mgmt task.

2024-10-24 05:47 UTC, Bhavneet-Sharma commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +- name: Add certificate file for PowerFlex version 4.x
Suggestion:
Please try to re-use the module tasks as we're developing the modules.

2024-10-24 13:13 UTC, RayLiu7 commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +- name: Add certificate file for PowerFlex version 4.x
It sounds good to use SDT module when it's available. I think I will consider the replacement and redo the testing if the time for the release is permitted after the SDT module is completed. But for now, I would suggest we keep the CLI commands. After all, they work fine and are used in other roles as well.

2024-10-24 13:13 UTC, RayLiu7 commented on roles/powerflex_sdt/vars/main.yml
> +powerflex_role_environment:
It's used in powerflex_common for the installation of rpms

2024-10-24 13:21 UTC, RayLiu7 commented
Hi @trisha-dell, just a kind reminder, please help communicate the comments we reviewed together in the last interlock with @sachin-apa. I'll do the modifications after we reach a consensus. Thank you~

2024-10-28 07:04 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +  when: ansible_distribution in ("RedHat", "CentOS", "SLES")
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/gather_facts_module.html

2024-10-31 09:14 UTC, RayLiu7 commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +  ignore_errors: true
Removed and added failed_when to manage idempotency.

2024-10-31 09:16 UTC, RayLiu7 commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +  when: ansible_distribution in ("RedHat", "CentOS", "SLES")
Task added to get ansible_distribution as suggested.

2024-10-31 09:25 UTC, RayLiu7 commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +  ansible.builtin.command: scli --add_certificate --certificate_file /opt/emc/scaleio/mdm/cfg/mgmt_ca.pem
Good suggestion. As discussed in the interlock, due to the limitation of time for this release, we suggest move this code refactoring into the future release. We're going to create a ticket to track it. Is there any parent ticket to manage this kind of tasks that we can attach the ticket to?

2024-11-06 06:29 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/install_sdt.yml
> +  ansible.builtin.command: scli --add_certificate --certificate_file /opt/emc/scaleio/mdm/cfg/mgmt_ca.pem
Not, Yet i will make a not of this and create a ticket once we have a common project. Good to go for now.

2024-11-06 06:57 UTC, sachin-apa commented
run e2e

2024-11-06 08:26 UTC, Bhavneet-Sharma approved these changes

2024-11-06 12:23 UTC, sachin-apa approved these changes

2024-11-06 12:23 UTC, sachin-apa commented on roles/powerflex_sdt/tasks/uninstall_sdt.yml
> +  ignore_errors: true
```suggestion
```

2024-11-08 02:36 UTC, RayLiu7 commented
Sonar and Checkmarx report
Sonar: https://sonarqube1.cec.lab.emc.com/dashboard?branch=64&id=ansible-powerflex
Checkmarx: https://osj-sio-03-prd.cec.lab.emc.com/job/Ansible-PowerFlex-CheckMarx/

2024-11-20 07:27 UTC, meenakshidembi691 approved these changes

2024-11-20 07:36 UTC, merged