Support NVMe host management
dell/ansible-powerflex pull request #68
Opened 2024-10-25 03:25 UTC by P-Cao

# Description
Add support for management of NVMe host

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, pep8, linting, or security issues
- [x] I have performed Ansible Sanity test using --docker default
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit Test
Name                                                                        Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------------------------------------------
plugins/modules/info.py                                                       346      3    116     16    96%
plugins/modules/nvme_host.py                                            146      3     42      5    96%

2024-10-25 03:26 UTC, ansible-collections-svc commented
Can one of the admins verify this patch?

2024-10-29 07:56 UTC, Bhavneet-Sharma requested changes
Please have a look at sonar issues and apply fix.

2024-10-29 07:56 UTC, Bhavneet-Sharma commented on plugins/modules/nvme_host.py
> +        state=dict(required=True, type="str", choices=["present", "absent"]),
```suggestion
        state=dict(default='present', type="str", choices=["present", "absent"]),
```

2024-10-29 07:56 UTC, Bhavneet-Sharma commented on plugins/modules/nvme_host.py
> +                msg = f"Please provide valid {param}"
Remove please keyword from each error message,
```suggestion
                msg = f"Provide valid {param}"
```

2024-10-29 07:56 UTC, Bhavneet-Sharma commented on plugins/modules/nvme_host.py
> +                msg = f"Please provide valid {param}"
Applicable for all such occurrences.

2024-10-29 07:56 UTC, Bhavneet-Sharma commented on plugins/modules/nvme_host.py
> +        if nvme_host_new_name:
As per Anupam's suggestion, We'll allow users to pass rename parameter in the playbook.
Flow will be like this: module will first do the create call, if it found any modification module should perform the modify call.

2024-10-29 07:56 UTC, Bhavneet-Sharma commented on plugins/modules/nvme_host.py
> +    def remove(self, nvme_id):
Use proper name to identify the method.
```suggestion
    def remove_nvme(self, nvme_id):
```

2024-10-29 07:56 UTC, Bhavneet-Sharma commented on plugins/modules/nvme_host.py
> +    def perform_module_operation(self):
Instead of perform_module_operation, Please use the following design patterns  like we have used same in all new module, 

Reference here: https://github.com/dell/ansible-powerscale/blob/main/plugins/modules/alert_channel.py#L700

This pattern helps to reduce the complexity of code.

2024-10-29 09:02 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +        if nvme_host_new_name:
So, if it does have both name and new_name, It would first create and then modify the name in one operation right?

2024-10-30 12:16 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +version_added: '1.0.0'
Fixed

2024-10-30 12:16 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +    - Maximum number of paths per volume. Used to create/modify the NVMe host.
Fixed

2024-10-30 12:17 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +notes:
Check mode is supported now

2024-10-30 12:17 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +        "nqn": "nqn.2014-08.org.nvmexpress:uuid:79e90a42-47c9-a0f6-d9d3-51c47c72c7c1",
Updated

2024-10-30 12:17 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +            supports_check_mode=False,
Supported

2024-10-30 12:17 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +        state=dict(required=True, type="str", choices=["present", "absent"]),
Done

2024-10-30 12:18 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +                msg = f"Please provide valid {param}"
Done

2024-10-30 12:18 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +    def remove(self, nvme_id):
Done

2024-10-30 12:19 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +    def perform_module_operation(self):
Updated the pattern

2024-11-04 04:35 UTC, sachin-apa commented on plugins/modules/nvme_host.py
> +notes:
Please refer new ansible guidelines on documneting check and diff mode.
https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-fields

2024-11-04 05:59 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +notes:
Use Attribute now

2024-11-06 06:30 UTC, trisha-dell commented on plugins/modules/nvme_host.py
> +    contains:
The sample mentions many parameters. Please add all of these in the returned details.

2024-11-06 06:36 UTC, trisha-dell commented on plugins/modules/nvme_host.py
> +def main():
diff mode implementation seems to be missing.

2024-11-06 06:57 UTC, sachin-apa commented
run e2e

2024-11-06 09:44 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +def main():
Supported

2024-11-06 09:44 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +    contains:
Added

2024-11-06 12:02 UTC, sachin-apa commented on plugins/modules/nvme_host.py
> +                LOG.info(msg=f"Failed to remove NVMe host {nvme_host_id}")
Does this log correct here ? Please check.

2024-11-06 12:06 UTC, sachin-apa approved these changes

2024-11-08 03:12 UTC, P-Cao commented
SonarQube report:
![image](https://github.com/user-attachments/assets/69589345-1a81-4bb4-86b2-f46bc9d665dc)
CheckMarx report:
https://osj-sio-03-prd.cec.lab.emc.com/job/Ansible-PowerFlex-CheckMarx/25/
![image](https://github.com/user-attachments/assets/e1c00429-dfb0-4cbb-bb2e-d9688e375b95)

2024-11-08 06:29 UTC, Bhavneet-Sharma commented on plugins/modules/nvme_host.py
> +- Managing NVMe hosts on PowerFlex storage system includes getting details of NVMe hosts
```suggestion
- Managing NVMe hosts on PowerFlex storage system includes creating, getting details of NVMe hosts
```

2024-11-08 06:29 UTC, Bhavneet-Sharma commented on plugins/modules/nvme_host.py
> +  and renaming NVMe hosts.
```suggestion
  , modifying and deleting NVMe hosts.
```

2024-11-08 06:29 UTC, Bhavneet-Sharma commented on tests/unit/plugins/module_utils/mock_nvme_host_api.py
> +Mock Api response for Unit tests of NVMe host module on Dell Technologies (Dell) PowerFlex
```suggestion
Mock Api response for Unit tests of NVMe host module on Dell Technologies PowerFlex
```

2024-11-08 10:00 UTC, P-Cao commented on plugins/modules/nvme_host.py
> +- Managing NVMe hosts on PowerFlex storage system includes getting details of NVMe hosts
Updated

2024-11-08 10:00 UTC, P-Cao commented on tests/unit/plugins/module_utils/mock_nvme_host_api.py
> +Mock Api response for Unit tests of NVMe host module on Dell Technologies (Dell) PowerFlex
Updated

2024-11-13 08:04 UTC, Bhavneet-Sharma approved these changes

2024-11-19 10:07 UTC, trisha-dell approved these changes

2024-11-20 07:27 UTC, meenakshidembi691 approved these changes

2024-11-20 07:37 UTC, merged