Implement SDT Module
dell/ansible-powerflex pull request #69
Opened 2024-10-30 02:29 UTC by RayLiu7

# Description
Implement SDT Module
- Managing SDT on PowerFlex storage system:
  creating new SDT, getting details of SDT, managing IP/role of SDT,
  modifying attributes of SDT, and deleting SDT.
Code Coverage: 
![image](https://github.com/user-attachments/assets/423e1fcd-3e3a-469d-9f8a-2145106f60db)
![image](https://github.com/user-attachments/assets/7a7e682f-e90d-4fcb-859a-ff519c265462)

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, pep8, linting, or security issues
- [x] I have performed Ansible Sanity test using --docker default
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit Tests

2024-10-30 02:31 UTC, ansible-collections-svc commented
Can one of the admins verify this patch?

2024-11-04 07:21 UTC, RayLiu7 commented on plugins/modules/sdt.py
> +notes:
It supports check mode. Updated underneath.

2024-11-06 06:40 UTC, trisha-dell commented on plugins/modules/sdt.py
> +  state:
state should be optional with default as present.

2024-11-06 06:57 UTC, sachin-apa commented
run e2e

2024-11-06 08:18 UTC, Bhavneet-Sharma requested changes

2024-11-06 09:06 UTC, RayLiu7 commented on plugins/modules/sdt.py
> +                error_msg = "sdt_new_name and maintenance_mode are not supported during SDT creation"
Hi @Bhavneet-Sharma, we had a agreement with Shrinidhi and Sachin to move modifying operations (like enter maintenance mode and rename) out of creation during the spike demo session, considering user usually have a sequence of steps to do in a playbook, so it's better to keep the atomicity of operations.

2024-11-06 09:09 UTC, RayLiu7 commented on plugins/modules/sdt.py
> +            error_msg = "Please provide valid sdt_name value for the creation of SDT."
Could you tell me why we don't want to use please in the msg? Just curious

2024-11-06 09:34 UTC, Bhavneet-Sharma commented on plugins/modules/sdt.py
> +                error_msg = "sdt_new_name and maintenance_mode are not supported during SDT creation"
Hi @RayLiu7,
We had review comment from Anupam to not to through an error message when rename parameter is passed while creating the object.

2024-11-06 09:37 UTC, Bhavneet-Sharma commented on plugins/modules/sdt.py
> +            error_msg = "Please provide valid sdt_name value for the creation of SDT."
We had IDD review comment in the past about this. They said is not a best practice to add please error message.

2024-11-07 02:42 UTC, RayLiu7 commented on plugins/modules/sdt.py
> +                error_msg = "sdt_new_name and maintenance_mode are not supported during SDT creation"
@sachin-apa @Bhavneet-Sharma ok, I'll remove the error display and ignore the params not applicable for create.

2024-11-07 04:01 UTC, RayLiu7 commented on plugins/modules/sdt.py
> +                error_msg = "sdt_new_name and maintenance_mode are not supported during SDT creation"
@sachin-apa Just to confirm, by ignoring the params not for create, we don't perform the rename or mode change in the this task, right?

2024-11-07 09:21 UTC, RayLiu7 commented on plugins/modules/sdt.py
> +notes:
Added diff support and updated attributes

2024-11-08 02:39 UTC, RayLiu7 commented
Sonar and Checkmarx report
Sonar: https://sonarqube1.cec.lab.emc.com/dashboard?id=ansible-powerflex&branch=69
Checkmarx: https://osj-sio-03-prd.cec.lab.emc.com/job/Ansible-PowerFlex-CheckMarx/22/

2024-11-08 02:40 UTC, RayLiu7 commented on plugins/modules/sdt.py
> +                error_msg = "sdt_new_name and maintenance_mode are not supported during SDT creation"
Fixed

2024-11-08 06:56 UTC, Bhavneet-Sharma commented on plugins/modules/sdt.py
> +""" Ansible module for managing SDT on Dell Technologies (Dell) PowerFlex"""
```suggestion
""" Ansible module for managing SDT on Dell Technologies PowerFlex"""
```

2024-11-08 06:56 UTC, Bhavneet-Sharma commented on tests/unit/plugins/module_utils/mock_sdt_api.py
> +Mock Api response for Unit tests of SDT module on Dell Technologies (Dell) PowerFlex
```suggestion
Mock Api response for Unit tests of SDT module on Dell Technologies PowerFlex
```

2024-11-13 08:18 UTC, Bhavneet-Sharma approved these changes

2024-11-19 07:52 UTC, sachin-apa approved these changes

2024-11-19 10:09 UTC, trisha-dell approved these changes

2024-11-20 07:28 UTC, meenakshidembi691 approved these changes

2024-11-20 08:25 UTC, merged